# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sources/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(860, 635)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAcceptDrops(True)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("* {background: rgb(248, 248, 249);}\n"
"\n"
"QLabel {\n"
"    color: #121212;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QComboBox,\n"
"QPushButton,\n"
"QTableView,\n"
"QLineEdit {\n"
"    border-color: #d9dadb;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #121212;\n"
"}\n"
"\n"
"QPushButton,\n"
"QTableView,\n"
"QLineEdit,\n"
"QComboBox:editable {\n"
"    background: #fff;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    border-top-right-radius: 5px;\n"
"    border-top-left-radius: 5px;\n"
"    background: #f2f2f3;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: #f2f2f3;\n"
"    border: none;\n"
"    border-right: 1px solid #d9dadb;\n"
"    border-bottom: 1px solid #d9dadb;\n"
"}\n"
"\n"
"QHeaderView::section:selected {\n"
"    color: #000;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"QTableView {\n"
"    outline: 0;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background:  rgba(47, 141, 255, 30);\n"
"    color: #000;\n"
"}\n"
"\n"
"QComboBox,\n"
"QLineEdit {\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QComboBox:!editable {\n"
"    background: #e8e8e9;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 18px;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding-right: 6px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(images/down_arrow.svg);\n"
"}\n"
"\n"
"QPushButton {\n"
"    padding: 3px 7px\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: #2d2d2f;\n"
"    background: #d9d9da;\n"
"    border-color: #c3c5c6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #f4f4f5;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.app_name_label = QtWidgets.QLabel(self.centralwidget)
        self.app_name_label.setGeometry(QtCore.QRect(50, 34, 321, 51))
        self.app_name_label.setStyleSheet("font-weight: 600;\n"
"font-size: 16pt;\n"
"font-family: Kontor, Nunito, sans-serif;\n"
"color: #000;")
        self.app_name_label.setObjectName("app_name_label")
        self.videos_table_widget_label = QtWidgets.QLabel(self.centralwidget)
        self.videos_table_widget_label.setGeometry(QtCore.QRect(53, 108, 221, 21))
        self.videos_table_widget_label.setStyleSheet("")
        self.videos_table_widget_label.setObjectName("videos_table_widget_label")
        self.add_video_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_video_button.setGeometry(QtCore.QRect(50, 411, 131, 31))
        self.add_video_button.setStyleSheet("")
        self.add_video_button.setObjectName("add_video_button")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(50, 547, 201, 51))
        self.start_button.setStyleSheet("QPushButton {\n"
"    font-size: 19px;\n"
"    background: rgb(253, 253, 253);\n"
"    border-width: 3px;\n"
"    border-radius: 9px;\n"
"    border-color: rgb(148, 164, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(244, 244, 244);\n"
"}")
        self.start_button.setObjectName("start_button")
        self.videos_table = QtWidgets.QTableView(self.centralwidget)
        self.videos_table.setGeometry(QtCore.QRect(50, 140, 761, 261))
        self.videos_table.setObjectName("videos_table")
        self.select_dir_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_dir_button.setGeometry(QtCore.QRect(50, 478, 141, 31))
        self.select_dir_button.setObjectName("select_dir_button")
        self.save_dir_label = QtWidgets.QLabel(self.centralwidget)
        self.save_dir_label.setGeometry(QtCore.QRect(200, 474, 591, 41))
        self.save_dir_label.setStyleSheet("")
        self.save_dir_label.setTextFormat(QtCore.Qt.PlainText)
        self.save_dir_label.setObjectName("save_dir_label")
        self.delete_video_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_video_button.setEnabled(False)
        self.delete_video_button.setGeometry(QtCore.QRect(190, 411, 131, 31))
        self.delete_video_button.setObjectName("delete_video_button")
        self.edit_video_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_video_button.setEnabled(False)
        self.edit_video_button.setGeometry(QtCore.QRect(330, 411, 131, 31))
        self.edit_video_button.setObjectName("edit_video_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyDownloader"))
        self.app_name_label.setText(_translate("MainWindow", "PyDownloader"))
        self.videos_table_widget_label.setText(_translate("MainWindow", "Видеоролики для скачивания:"))
        self.add_video_button.setText(_translate("MainWindow", "Добавить"))
        self.start_button.setText(_translate("MainWindow", "Начать скачивание"))
        self.select_dir_button.setText(_translate("MainWindow", "Выбрать папку"))
        self.save_dir_label.setText(_translate("MainWindow", "Выберите папку для сохранения файлов"))
        self.delete_video_button.setText(_translate("MainWindow", "Удалить"))
        self.edit_video_button.setText(_translate("MainWindow", "Редактировать"))
